title: What A Team
description: Celebrate your team's values together. A simple app for small teams to recognize each other through High Fives. Free on iOS and Android.
url: https://gariem.github.io
baseurl: /what-a-team-resources
